{% set name = "ai2-olmo-eval" %}
{% set version = "0.8.1" %}
{% set python_min = python_min|default("0.1a0") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ai2_olmo_eval-{{ version }}.tar.gz
  sha256: 63dfa43c828f721d6681e1a86edc442730cd3f7573fca544e72ca7990db1486c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy <2.0
    - pytorch
    - torchmetrics
    - datasets
    - tokenizers
    - scikit-learn
    - cached_path
    - requests
    - packaging
    - importlib-resources

test:
  imports:
    - olmo_eval
  commands:
    - pip check
  requires:
    - python ={{ python_min }}
    - pip

about:
  home: https://github.com/allenai/OLMo-Eval
  summary: In-loop evaluation tasks for language modeling
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
