{% set name = "ai2-olmo-eval" %}
{% set version = "0.9.0" %}
{% set python_min = python_min|default("0.1a0") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ai2_olmo_eval-{{ version }}.tar.gz
  sha256: a36d1210b921aabfbcefc3ecb704a7ac25adf25ae91f1c86343eff2bc142c6cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pytorch
    - torchmetrics
    - datasets >=3.6.0,<4
    - cached_path
    - requests
    - packaging
    - importlib_resources
    - tokenizers >=0.19.1,<0.23
    - pyarrow >=19.0,<20

test:
  imports:
    - olmo_eval
  commands:
    - pip check
  requires:
    - python ={{ python_min }}
    - pip

about:
  home: https://github.com/allenai/OLMo-Eval
  summary: In-loop evaluation tasks for language modeling
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
